library(tidyverse)
path <- "D:/Datascience/Projects/DataScienceJHU-/household_power_consumption.txt"
household_power_consumption <- read.table(path, header = TRUE, sep = ";")
household_power_consumption$Date <- strptime(household_power_consumption$Date, format = "%d/%m/%Y")
data <- subset(household_power_consumption, Date == "2007-02-01" | Date == "2007-02-02")
data$Global_active_power <- as.numeric(data$Global_active_power)
data$date_time <- ymd_hms(paste(data$Date, data$Time))
data$Sub_metering_1 <- as.numeric(data$Sub_metering_1)
data$Sub_metering_2 <- as.numeric(data$Sub_metering_2)
data$Sub_metering_3 <- as.numeric(data$Sub_metering_3)
png(filename = "plot4.png", width = 480, height = 480)
par(mfrow = c(2, 2))
plot(data$date_time,data$Global_active_power, type = "l",xlab = "Datetime", ylab = "Global Active Power")
plot(data$date_time,data$Voltage, type = "l",xlab = "Datetime", ylab = "Voltage")
plot(data$date_time,data$Sub_metering_1, type = "n",xlab = "Datetime", ylab = "Energy sub metering")
lines(data$date_time,data$Sub_metering_1)
lines(data$date_time,data$Sub_metering_2, col = "red")
lines(data$date_time,data$Sub_metering_3, col = "blue")
legend("topright", c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"), col = c("black", "red", "blue"), lty = c(1, 1, 1))
plot(data$date_time,data$Global_reactive_power, type = "l",xlab = "Datetime", ylab = "Global_reactive_power")
dev.off()
